M48
; DRILL file {KiCad (7.0.0)} date Fri Apr 14 16:10:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-14T16:10:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.6654Y-2.3677
T1
G00X5.9429Y-2.3677
M15
G01X5.9547Y-2.3677
M16
G05
T0
M30
